export { default as AppMain } from './AppMain'
export { default as Navbar } from './Navbar/index.vue'
//export { default as Settings } from './Settings'
export { default as SideMenu } from './SideMenu/index.vue'
export { default as TagsView } from './TagsView/index.vue'
